services:
  app:
    user: "${USER_ID:-1000}"
    hostname: "${HOST_NAME:-ml-template}"
    image: data-versionning
    container_name: data-versionning-container
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        USER_NAME: "${USER_NAME:-ml-template}"
        USER_ID: "${USER_ID:-1000}"
        GIT_USER_NAME: "${GIT_USER_NAME:-john.doe@example.com}"
        GIT_USER_EMAIL: "${GIT_USER_EMAIL:-John Doe}"
    volumes:
      - ./:/app/
      - ~/.config/gcloud/:/home/${USER_NAME}/.config/gcloud
      - ~/.ssh:/home/${USER_NAME}/.ssh
    ipc: host
    init: true


